name: ci

on:
  push:

jobs:
  CI_pipeline:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          lfs: true
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      - name: Install uv
        uses: astral-sh/setup-uv@v3
      - name: Set up Python
        run: uv python install 3.12
      - name: Install the project
        run: uv sync --all-extras --dev
      - name: Run pre-commit
        uses: pre-commit/action@v3.0.1
      - name: Execute visualization notebooks once
        run: |
          cd apps
          uv run -- jupyter-nbconvert --execute --to python *.ipynb
      - name: Build container once
        uses: docker/build-push-action@v6
